version: '3.7'

services:
  kalilinux: 
    hostname: kalilinux.lab
    container_name: kali
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'csalab/kalilinux-docker:${VERSION:-latest}'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - SHELL=/bin/bash
      - PASSWORD=${PASSWORD:-kalilinux}
    volumes:
      - data:/home/kali/Desktop
    entrypoint: ["/bin/bash", "/startup.sh"]

volumes:
  data: {}