version: '3.7'
services:
  kalilinux:
    hostname: kalilinux.lab
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'kalilinux:web'
    restart: always
    ports:
      - 0.0.0.0:8080:8080
    working_dir: /root
    environment:
      - SHELL=/bin/bash
      - PASSWORD=kalilinux
    command: /bin/bash /startup.sh