version: '3.7'
services:
  kalilinux:
    hostname: burpsuite.lab
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'csalab/kalilinux-docker:${VERSION:-burpsuite}'
    restart: always
    ports:
      - 0.0.0.0:6080:6080
    environment:
      - SHELL=/bin/bash
      - PASSWORD=${PASSWORD:-burpsuite}
    entrypoint: ["/bin/bash", "/startup.sh"]
