version: 2.1

parameters:
  workflow:
    type: enum
    default: auto
    description: The workflow to trigger.
    enum: [auto, burpsuite]

executors:
  docker:
    docker:
      - image: cimg/base:stable
    resource_class: large

jobs:
  hadolint:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Checking Dockerfile code quality
          command: docker run --rm -i ghcr.io/hadolint/hadolint:latest < Dockerfile || true
  build-burpsuite:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker context create buildx-build
            docker buildx create --use buildx-build
            docker buildx build --push \
              --tag $DOCKER_REGISTRY/$REGISTRY_USER/kalilinux-docker:burpsuite \
              --platform linux/amd64,linux/arm64 \
              -f Dockerfile .

workflows:
  version: 2
  build-auto:
    when: { equal: [ auto, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
  build-burpsuite:
    when: { equal: [ burpsuite, << pipeline.parameters.workflow >> ] }
    jobs:
      - hadolint
      - build-burpsuite:
          requires:
            - hadolint
